const express = require("express");
const router = express.Router();
const clientController = require("../Controllers/clientController");
router.get("/getClients", clientController.getClients);
router.get("/getSpecificClient/:clientID", clientController.getSpecificClient);
router.get("/getMatchingClients", clientController.filterClients);
router.post("/addSuburb", clientController.addSuburb);
router.post("/addClients", clientController.addClient);
router.delete("/:clientID", clientController.deleteClient);
router.put("/:clientID", clientController.updateClient);
module.exports = router;
